name: Check Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release/*

  workflow_dispatch:

jobs:
  verifyPlugin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run Checks
        uses: coactions/setup-xvfb@v1
        with:
          run: ./gradlew check --stacktrace

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Verify Plugin
        run: ./gradlew verifyPlugin --stacktrace

